apiVersion: v1
kind: ConfigMap
metadata:
  name: wordpress-config
  namespace: secondary
data:
  WORDPRESS_DB_HOST: mysql-secondary-mahmoud123.mysql.database.azure.com:3306
  WORDPRESS_DB_NAME: wordpressdb